### ISSUE TITLE
CRUD pre zaznam trasy

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-nodejs-backend#1]
endpoint pre nastroj "prehliadac tras" na frontende.
v prvej verzii budeme podporovat iba format gpx, ale neskor chceme aj ine formaty (kmz).
v prvej verzii mame len anonymnych pouzivatelov.

tu je [zodpovedajuca issue pre frontend](https://github.com/FreemapSlovakia/freemap-v3-react/issues/101)

pouzivatel cez [nastroj prehliadac tras](http://next.freemap.sk/) nahra GPX, ta sa zobrazi. v menu pri zobrazenej trase by sme chceli mat tlacidlo "zdielat odkaz na trasu" ktore vygeneruje url. na to potrebujeme gpx nahrat na server a neskor ho zase ziskat.

### Nahrat GPX

```
POST /tracklogs/
```

request body bude JSON:

```
{
   "data": <string - b64 enkodovane gpx>,
   "mediaType": "application/gpx+xml",
   "name": <nazov povodneho suboru>
  }
```

response bude JSON:

```
{"uid": <string>}
```

UID ma 16 znakov ([a-zA-Z0-9]), lebo ho budeme davat do url.

### Ziskat GPX

```
GET /tracklogs/<uid>
```

v response body vrati json:

```
{
   "uid": <uid>,
   "data": <string - b64 enkodovane gpx>,
   "mediaType": "application/gpx+xml",
   "name": <nazov povodneho suboru>
  }
```

**Comment by zdila** [comment]
Navrhujem premenovat `b64data` na `data` a `format` na `mediaType`. A este by mohlo byt aj `GET /tracklogs/<uid>/file` co priamo poskytne GPX subor.

**Comment by petervojtek** [comment]
atributy som premenoval. ten priamo GET na gpx spravime hned ako to bude niekto/nieco potrebovat.
