### ISSUE TITLE
Support pre tracking z apky Traccar pre Android

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/freemap-v3-nodejs-backend#14]
Ahoj

 prosim pridat support pre payload z appky Traccar.
 V threade https://groups.google.com/g/osm_sk/c/BC5g37pmlRg/m/GNYUw9YlAQAJ dokonca clovek pise ze to funguje korektne z Traccar na IOS, avsak z Androidu mi to nejde.

Mam zapnute dve zariadenia ktore pravidelne posielaju data cez:
https://backend.freemap.sk/tracking/track/J7ihLyRf
https://backend.freemap.sk/tracking/track/sDIBtMf9
A budu posielat aj dalej kazdych 10-15 sekund, ak budu mat dobry signal.

Zial nemam prostriedky na zistenie struktury, skusal som vyrobit proxy cez Postman na localhoste, ale nejak tie post requesty nevidim, vidim iba bezne GET requesty ktore robim cez browser.

Ich support mi napisal ze:
"Traccar Client sends POST requests with parameters in the payload."
(https://www.traccar.org/forums/topic/custom-server/#post-45777)

  ahoj, Miro

**Comment by tjamecny** [comment]
Ahoj,
v logu vidim:
`"POST /tracking/track/J7ihLyRf/?id=...&timestamp=980027630&lat=...&lon=...&speed=0.0&bearing=0.0&altitude=...&accuracy=16.0&batt=44.0 HTTP/1.1" 400 41 "-" "Dalvik/1.6.0 (Linux; U; Android 4.1.2; GT-I8160 Build/JZO54K)"`
a
`"POST /tracking/track/sDIBtMf9?id=...&timestamp=1599343598&lat=...&lon=...&speed=0.29621358786678315&bearing=68.0&altitude=...&accuracy=96.0&batt=68.0 HTTP/1.1" 400 41 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.2; SM-G800F Build/NJH47F)"`

Vyzera to tak, ze posielas parametre ako GET (t.j. su viditelne v URL), namiesto POST (v tele requestu, cize neviditelne v logu).  To je asi aj dovod, preco to vracia "HTTP 400 Bad Request".

Priklad z logu pre ine zariadenie (HTTP 200 OK):
`"POST /tracking/track/h______p HTTP/1.1" 200 13 "-" "Locus Map/3.48.0/958 (Xiaomi,MI 4W,23)"`

**Comment by miro-janosik** [comment]
Ahoj

Fiha, posiela to aj stav baterky, typ telefonu, vsetko :-)
Moja otazka je, ci by bolo mozne akceptovat aj takyto typ vstupu, kedze je to tak napevno spravene v celkom jednoduchej a univerzalnej appke (ios, android) Traccar - https://www.traccar.org/client/ , a oni to zmenit/fixnut neplanuju (vid moj request vyssie)

Slubujem sa revansovat eurami alebo kryptomenami.
 ahoj, Miro

**Comment by tjamecny** [comment]
Som trochu zmateny: Na [tebou odkazovej stranke](https://www.traccar.org/forums/topic/custom-server/#post-45777) pisu, ze to nepodporuje argumenty v URL (t.j. "POST requests with parameters in the payload"), ale v logu vidim, ze od teba to chodi v URL! Takze bud oni nemaju pravdu (a posielaju to POST metodou s parametrami v URL, t.j. v GET formate), alebo ty mas v server URL zadane nieco ine ako len "server/tracking/track/id".

Ale vzhladom na to, ze tie jednotlive argumenty v URL su automaticky vyplnane hodnotami, tak zjavne to bude taky "mačkopes" v Traccar-e.

Nakodit sa to samozrejme da, ale ide to proti filozofii, ze pri GET parsujem URL a pri POST parsujem telo requestu.
Kazdopadne odporucam si to overit cez jednoduchy PHP skript, ktory vypise jednak GET argumenty a jednak POST, a URL tohto skriptu si nastavit v Traccar-e (skript musi vracat HTTP 200 OK). Po potvrdeni, ci sa jedna o "mačkopsa", alebo mi nieco uniklo, sa uvidi, co dalej.

**Comment by miro-janosik** [comment]
Ten nápad s PHP je dobrý, to viem spraviť, otestujem a napíšem čo posiela (ale predpokladám to isté ako prichádza k vám na server), IMHO je to mačkopes.

Nastavenia to nemá takmer žiadne - môžem tam nastaviť URL (mám tam to čo je v prvom príspevku - https://backend.freemap.sk/tracking/track/<token>), ID, frekvenciu, a parametre GPS kedy to má posielať.

**Comment by zdila** [comment]
> ale ide to proti filozofii, ze pri GET parsujem URL a pri POST parsujem telo requestu

Ani nie. Dat parametre do URL je uplne legitimne aj pre POST request.

**Comment by zdila** [comment]
Vyskusaj.

**Comment by miro-janosik** [comment]
Pre doplnenie, aplikacia na telefonoch je "Traccar Client" (od Anton Tananaev) verzia 6.3 z 2020-06-10.
Posielam cash.

**Comment by miro-janosik** [comment]
Chcel by som ale nahlasit, ze dnes od 9:00 to na jednom zariadeni prestalo fungovat ( https://backend.freemap.sk/tracking/track/J7ihLyRf ). Znova dostavam informaciu ze 'odosielanie zlyhalo'.
Prichadzaju tieto requesty? Maju nejake divne data?

Skusil som manualne ist cez browser na adresu https://backend.freemap.sk/tracking/track/J7ihLyRf (bez parametrov) a zariadenie ma pristup na web (dostal som informaciu "one or more values provided are not valid").

Druhe zariadenie funguje.

**Comment by zdila** [comment]
Problem s tym zariadenim bude ze posiela v `timestamp` hodnotu `980151304` a freemap nepodporuje hviezdny cas ;-).

**Comment by zdila** [comment]
Ak 980151304 je unix timestamp tak sa odkazuje takmer 20 rokov dozadu: 22.1.2001

**Comment by miro-janosik** [comment]
To je blaznive, cas telefonu je spravny, je nastavene ziskavanie zo siete (cez operatora), restartujem ho a uvidim ako sa bude spravat po restarte... po restate stale dostavam rovnaku hlasku.
Aj po odinstalovani aplikacie a zmazani jej dat (to som spravil o 13:55). Asi tam maju bug.

Prosim, bolo by mozne pridat fix tych dat - teda ze ak je timestamp 'out of bounds' tak akoby nebol vyplneny, aby to fungovalo?

**Comment by zdila** [comment]
Navrhujem najprv to reportovat Traccaru a ak to nebudu ochotni fixnut tak mozem u nas spravit workaround - asi akceptovat aj casy z dalekej minulosti. Ten timestamp je v tomto pripade dost cenna vec na zachovanie poradia uzlov. Ked som nasadil prvu podporu pre Traccar tak som videl ako appka chrli requesty s roznymi timestampami - co mala nacachovane.

**Comment by miro-janosik** [comment]
Takze uz je to jasne, vysvetlili to na https://www.traccar.org/forums/topic/timestamp-from-2001/ - je to zariadenim a chybou "GPS rollover" - https://www.gps.gov/support/user/rollover/ alebo https://github.com/barbeau/gpstest/blob/master/FAQ.md#why-is-my-gps-time-wrong . 
Z neznameho dovodu to (pravdepodobne) pred dvoma dnami vyslalo spravny timestamp (mozno preto ze zariadenie bolo dlho vypnute a nestihlo si updatnut data).
Potom sa prejavila tato chyba, a odvtedy vysiela nespravny timestamp, nepomaha ani 'resetnutie GPS-A dat' a podobne akcie co som skusal.

Je to stare zariadenie (Samsung Galaxy Ace 2 I8160) a updaty OS nan uz nie su, takze chybu ani nemam ako opravit.
Takze je na mieste otazka - tato chyba pravdepodobne zasiahne viacero starsich zariadeni a najstarsie nedostanu updates. GPS suradnice ukazuje celkom dobre, ale cas je nespravny.

Takze by som rad poprosil o workaround, nasiel som ze je na to univerzalny:
>  timestamp += 619315200  (pre unixtime timestamp v sekundach)
ktory bude fungovat 20 rokov ;-) pripadne s pridanym cyklom aj na n*20 rokov ;-)

(prevzate z https://stackoverflow.com/questions/56147606/wrong-date-returned-from-location-gettime-after-6-april-2019-week-number-rollov/56357981#56357981 )

**Comment by zdila** [comment]
skus teraz

**Comment by miro-janosik** [comment]
Vdaka, fixnute. Vidim ze prislo vela poloh z predchadzajucich dni, a aj dnesne polohy uz zobrazuje spravne.
Dakujem.
