### ISSUE TITLE
Nefunguje prihlásenie pomocou Google účtu v Chromium browseri

### ISSUE THREAD

**Issue by tjamecny** [FreemapSlovakia/freemap-v3-nodejs-backend#15]
Pri prihlasovaní pomocou Google účtu v Chromium 91.0.4452.0:
- prvý request (OPTIONS) na /auth/login-google vráti kód 204
- druhý request (POST) na /auth/login-google s vyplneným "idToken" vráti chybu 500

Vo Firefoxe 87.0 prihlásenie funguje bez problémov:
- prvý request (OPTIONS) na /auth/login-google vráti kód 204
- druhý request (POST) na /auth/login-google s vyplneným "idToken" vráti kód 200

**Comment by tjamecny** [comment]
Doplnenie: Firefox bežne používam, a bol som v minulosti už na freemap.sk prihlásený (cez OSM konto), takže rozdiel môže byť aj v uložených cookies alebo local storage. V Chromiu som doteraz prihlásený nebol.

**Comment by zdila** [comment]
Mne ide aj v Chromiume, skusil som v nom aj v inkognito mode. A to mam na google 2FA.

**Comment by zdila** [comment]
nieco som nasiel v logoch, skusim fixnut

**Comment by zdila** [comment]
fixnute v 1a509919c4f42133480c1948de07ffdd87d86b34
