### ISSUE TITLE
Move from OAuth 1.0a to OAuth 2.0 for OSM logins

### ISSUE THREAD

**Issue by mmd-osm** [FreemapSlovakia/freemap-v3-nodejs-backend#16]
OSM's OAuth 1.0a is in the process of being deprecated, as discussed at https://github.com/openstreetmap/operations/issues/867. No timeline has been set, but we do not expect to shut off OAuth 1.0a this year. It would be good to move to OAuth 2.0 well before this time.

**Comment by zdila** [comment]
Fixed in eaf25bfa40074e81487fc8097301d8d586510696 and https://github.com/FreemapSlovakia/freemap-v3-react/commit/3ff68798cd1a931a650609d2d1e0c284ce148b9b
