### ISSUE TITLE
aku databazu pouzit?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-nodejs-backend#2]
Martin @zdila, pre ucely gpx uploadu by som originalny nazov subor (a neskor dalsie metadata, napr. owner, permissions) rad ukladal do nejakej db. v principe hocijaky key-value store s perzistenciou.
neviem odhadnut co vsetko ine v db bude, t.j. ako bude velka. odhadujem ze pri galerii obrazkov budes mat samotne fotky na disku a v db budu len metadata.

ja mam skusenost s tymto: https://github.com/techfort/LokiJS, ale to je na uvod mozno overkill (a nepouzil som to na viac ako 1000 zaznamov, takze neviem posudit aku to ma vykonnost).

**Comment by tjamecny** [comment]
Kedze planujeme nasadit Nominatim, bude na serveri dostupna aj PostgreSQL DB (a existujucu MariaDB asi zrusime).

**Comment by zdila** [comment]
Ja som v pohode s MySQL / PostgreSQL. Ziadnu HipsterDB podla mna na nase ucely netreba ;-)

Ta LokiJS je naviac in-memory a nam asi treba on-disk.

**Comment by petervojtek** [comment]
ok, postgres je v pohode, len potom by sme mali este pouzit nieco na manazovanie migracii (ja som postgres pouzival vzdy iba z rails kde boli migracie zadarmo, takze v nodejs neviem co sa oplati).
