### ISSUE TITLE
Nezobrazuje náhľady pri nahrávaní obrázkov

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-v3-nodejs-backend#4]
Používam prehliadač Opera 47

tu je výpis s JS konsoly:
galleryUploadModal.bundle.js:1 
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at i (http://next.freemap.sk/galleryUploadModal.bundle.js:1:216)
    at http://next.freemap.sk/galleryUploadModal.bundle.js:1:2928
    at <anonymous>

**Comment by zdila** [comment]
vdaka za report, asi opravene.

**Comment by zdila** [comment]
PS: toto zas patri do https://github.com/FreemapSlovakia/freemap-v3-react/issues

ak vidis javascriptovy chybu je to frontend, ak server vratil 500 je to backend.

**Comment by seg-on** [comment]
Je to aj nasadené? lebo mi to stále hlási.

**Comment by zdila** [comment]
prosim posli mi obrazok (mailom) ktory ti to robi

**Comment by zdila** [comment]
Skus teraz

**Comment by seg-on** [comment]
super už to ide :)
